name: eval-visualization
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - jupyter
  - notebook
  - ipykernel
  - pip
  - pip:
      - mpl_toolkits
      - ipywidgets
