if(EXISTS "/home/trunt/BA/fbuild/GraphicsProject_tests[1]_tests.cmake")
  include("/home/trunt/BA/fbuild/GraphicsProject_tests[1]_tests.cmake")
else()
  add_test(GraphicsProject_tests_NOT_BUILT GraphicsProject_tests_NOT_BUILT)
endif()
